### PR TITLE
Remove uppercase chars from valid hostnames

### LINKED ISSUE #327: Every couple weeks I get Error 1003
### The problem

Cloudflared works great then every couple weeks gets this error and I have to log into Cloudflare, delete the DNS CName entry, and restart Cloudflared add-on.
  

Screenshot 2023-02-20 145539
Screenshot 2023-02-20 145512

### What version of Cloudflared has the issue?

4.0.10

### What was the last working version of Cloudflared?

_No response_

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: <Redacted> // it is just my personal domain name
```

### Anything in the logs that might be useful for us?

_No response_

### Steps to reproduce the issue

Everything works perfectly, then every week or couple weeks, it gets the error shown in the screenshots above.  It's like the add-on is trying to make a new tunnel when there's already one there that it made before.  I'll note that I do not do anything else with Cloudflare or this domain except use it as documented for the add-on.

### Additional information

_No response_

### LINKED ISSUE #342: Need to delete cloudflare DNSs everytime before i restart the addon
### The problem

I had the same problem problem described in issue #259 tonight.  Long story short, after installing and configuring the add-on, the tunnel is created successfully.  However at the next restart it fails to create the DNS entry with this message in the log:

[09:38:09] INFO: Creating DNS entry ###.###.tk...
Failed to add route: code: 1003, reason: An A, AAAA, or CNAME record with that host already exists.
[09:38:11] FATAL: Failed to create DNS entry ###.###.tk.

The problem is when the "external_hostname" is written in CAPITALS, you will have the issue, because the CNAME DNS entry in the Cloudflare Portal is stored in lowercase. 

At the next load, when the hostname is compared with existing DNS entries, the comparaison fails because the verification is probably case sensitive, then it tries to recreate the entry and fails because it already exists.

### What version of Cloudflared has the issue?

4.0.12

### What was the last working version of Cloudflared?

_No response_

### What type of installation are you running?

Home Assistant Supervised

### Add-on YAML Configuration

_No response_

### Anything in the logs that might be useful for us?

```txt
[09:38:09] INFO: Creating DNS entry ###.###.tk...
Failed to add route: code: 1003, reason: An A, AAAA, or CNAME record with that host already exists.
[09:38:11] FATAL: Failed to create DNS entry ###.###.tk.
```

### Steps to reproduce the issue

In an existing installation, if the hostname is written in capitals (ex. HOST.domain.com), the add-on will fail to load.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brenner-tobias**
# Proposed Changes

Not allow uppercase characters in hostnames (external_hostname and in additional_hosts)

## Related Issues

Closes #342 
Closes #327

### CODE REVIEW

File: cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@ checkConfig() {
     bashio::log.trace "${FUNCNAME[0]}"
     bashio::log.info "Checking add-on config..."
 
-    local validHostnameRegex="^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$"
+    local validHostnameRegex="^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$"
```
Comment (elcajon) [inline cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh:17]: If the regex is changed, the error message after an unsuccessful check would probably have to be changed as well, right? Alternatively, it would also be possible to simply convert the string by using `bashio::string.lower`

Comment (brenner-tobias) [reply cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh:17]: Agreed, I did include the message in my last commit. I also thought about simply changing it, but I would only do this if we are also able to actually change the config entry itself and not just write lowercase to Cloudflare. To do that is not super simple, especially for the additional_hosts array.
So I think it is easier and also clearer to just print the error message and have the users change it. Happy to hear your suggestion though

**Review by elcajon — APPROVED** [review]
